### ISSUE TITLE
Only half of screen works

### ISSUE THREAD

**Issue by xxv** [anupam1525/AcrylicPaint#2]
When I draw, only half of screen seems to be saved to the canvas. It draws the stroke, but then immediately erases it on the bottom half of the screen (or so) there's also a small margin on the right side that behaves similarly.

**Comment by valerio-bozzolan** [comment]
Hello @anupam1525! Nice to see you again! How are you? Where have you been? :see_no_evil:

**Comment by anupam1525** [comment]
> Hello @anupam1525! Nice to see you again! How are you? Where have you been? 🙈

hey @valerio-bozzolan thank you for keeping this project alive. As this project is way too old for its maturity was thinking of getting studio project in place. Visited the project post your PR merge but was unable to build it properly. Will raise a PR i few days for it. Keep an eye out 😄
